version: '3.1'

services:
  users-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=lera
      - POSTGRES_DB=users
    ports:
      - "27001:5432"
    volumes:
      - ./server_user/init.sql:/docker-entrypoint-initdb.d/init.sql
  users-server:
    image: noskool-users
    network_mode: "host"
    ports:
      - "9992:9992"